In [6]:
import numpy as np
#data procceing and reading the data
import pandas as pd 
#data vusuazaltion
import matplotlib.pyplot as plt
#create accuracy and diagrams
import seaborn as sns 

In [7]:
data=pd.read_csv('USA_Housing.csv')
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [8]:
data.drop(columns=["Address"],axis=1,inplace=True)
# data.drop(columns=["Unnamed: 0","year","month"],axis=1,inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB


In [9]:
data.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB


In [11]:
X=data.iloc[:,:-1]
y=data['Price']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [13]:
from sklearn.preprocessing import MinMaxScaler
# scaler=StandardScaler()
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

# x_train=scaler.fit_transform(X_train)
# y_train=scaler.fit_transform(y_train)


In [14]:
X_train

array([[0.43091002, 0.18763801, 0.81275567, 0.52888889, 0.6070962 ],
       [0.51215059, 0.55700721, 0.62624585, 0.26444444, 0.65998844],
       [0.68520905, 0.39854502, 0.71083283, 0.24666667, 0.35307175],
       ...,
       [0.55690809, 0.55952358, 0.47923756, 0.25333333, 0.51259253],
       [0.47059858, 0.68924723, 0.85653117, 0.51555556, 0.70362008],
       [0.4989978 , 0.47004852, 0.65934704, 0.89777778, 0.49367042]])

In [15]:
from sklearn.neighbors import KNeighborsRegressor
k=5
knn=KNeighborsRegressor(n_neighbors=k)
knn

KNeighborsRegressor()

In [16]:
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [17]:
# from sklearn.linear_model import LinearRegression
# re=LinearRegression()
# re.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [18]:

y_pred

array([1084273.0726624 , 1035436.00232614,  979382.5100229 , ...,
       1230245.9139287 , 1387213.46918344,  853010.30114892])

In [19]:
from sklearn.metrics import accuracy_score
accuaracy=knn.score(X_test,y_test)
accuaracy

0.5380597662219821

In [20]:
#evaluate the accuracy for diff values of k
accuaracies=[]
k_values=range(1,25)
for k in k_values:
  knn=KNeighborsRegressor(n_neighbors=k)
  knn.fit(X_train,y_train)
  accuaracy=knn.score(X_test,y_test)
  accuaracies.append(accuaracy)

accuaracies

[0.36550779633211306,
 0.46707562975628425,
 0.5015403695438537,
 0.530851792354436,
 0.5380597662219821,
 0.5502702928443151,
 0.5555923450214448,
 0.5652152945551127,
 0.5716397776272182,
 0.5770454501235982,
 0.5826882129331638,
 0.588289213616922,
 0.5890701791596261,
 0.5913599534743018,
 0.593029321514442,
 0.5967426904941422,
 0.5981303654736785,
 0.5985396734245186,
 0.6008936665341118,
 0.601591195340517,
 0.6037663816657688,
 0.6063907151068169,
 0.607164992170361,
 0.6088224362551331]

In [21]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

54513716722.38167
201355.6384851416
233481.72674190515


In [22]:
#new data
x_new=[[79545.558574,5.682861,735436.00232614,979382.5100229,1.059034e+06],
    [6,120,64,32,0]]

#scaling
x_new_scaled=scaler.fit_transform(x_new)
#predictions dor new data
y_pred_new=knn.predict(x_new_scaled)

In [23]:
y_pred

array([1084273.0726624 , 1035436.00232614,  979382.5100229 , ...,
       1230245.9139287 , 1387213.46918344,  853010.30114892])